// This file was generated by Prisma, and assumes you have installed the following:
import { defineConfig } from 'prisma/config';
import fs from 'node:fs';
if (fs.existsSync('.env')) process.loadEnvFile('.env');

const dbUser = process.env.DATABASE_USER;
const dbPassword = process.env.DATABASE_PASSWORD;
const dbHost = process.env.DATABASE_HOST;
const dbPort = process.env.DATABASE_PORT;
const dbName = process.env.DATABASE_NAME;

const constructedUrl = `mysql://${dbUser}:${dbPassword}@${dbHost}:${dbPort}/${dbName}`;

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: constructedUrl,
  },
});
