// This file was generated by Prisma, and assumes you have installed the following:
import { defineConfig } from 'prisma/config';
import { env } from './src/lib/server/env';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env.DATABASE_URL,
  },
});
