auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

analytics:
  reporting_enabled: false

ingester:
  # 核心防丢配置：开启预写日志，不要指定 dir，它会自动进入 /loki/wal
  wal:
    enabled: true

  # 核心防丢配置：优化内存 Chunk 的生存期与刷盘频率
  chunk_idle_period: 2h
  max_chunk_age: 1h
  chunk_target_size: 1572864
  chunk_block_size: 262144
  flush_check_period: 10s
  flush_op_timeout: 10s
